collab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('siteapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

collab_suite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('suiteapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

siteapp/urls.py
from django.urls import path
from . import views

app_name = 'siteapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('sites/', views.sites, name='sites'),
    path('task/', views.task, name='task'),
    path('repository/', views.repository, name='repository'),
    path('taskpage/', views.taskpage, name='taskpage'),
    path('add_site_member/', views.add_site_member, name='add_site_member'),
    path('delete/<str:pk>', views.deleteFile, name='deleteFile'),
    path('deleteSite_Folder/??/=+/<str:pik>/???!!t4/piAss', views.deleteSite_Folder, name='deleteSite_Folder'),
]

siteapp/models.py
from django.db import models


# Create your models here.
class File(models.Model):
    file_id = models.AutoField(primary_key=True)
    filepath = models.FileField(upload_to='files/', null=True, verbose_name="")
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.file_id) + ":" + str(self.filepath)


class Site(models.Model):
    site_name = models.CharField(max_length=200)
    site_id = models.CharField(max_length=200, primary_key=True)
    description = models.TextField()
    site_visibilty = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)


class Task(models.Model):
    priority = models.CharField(max_length=7)
    deadline = models.DateTimeField()
    assignee = models.CharField(max_length=200)
    comment = models.TextField


class Taskfile(models.Model):
    task_file = models.FileField(upload_to='files/', null=True, verbose_name="")


class Folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    folder_name = models.CharField(max_length=255, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    # created_by =


class Site_Folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    folder_name = models.CharField(max_length=255, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)

siteapp/forms.py
from django import forms
from .models import *


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ["filepath"]


CHOICES = [('private', 'Private'),
           ('medium', 'Medium'),
           ('public', 'Public')]


class SiteForm(forms.ModelForm):
    site_visibility = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
    site_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter the name of the site...'}))
    site_id = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'site id...'}))
    # description = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter a description for the
    # site...'}))

    class Meta:
        model = Site
        fields = ["site_name", "site_id", "description", 'site_visibility']


class FolderForm(forms.ModelForm):
    folder_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter the folder name...'}))

    class Meta:
        model = Folder
        fields = ['folder_name']


class Site_FolderForm(forms.ModelForm):
    folder_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter the folder name...'}))

    class Meta:
        model = Site_Folder
        fields = ['folder_name']

# select for dropdown
# choice for radio button

tempapp/views.py
from django.shortcuts import render

# Create your views here.

tempapp/templates/assign.html
<!--Assignees modal -->
      <div class="container">
        <!-- The Modal -->
        <div class="modal row" id="assignModal">
          <div class="assign-modal-dialog col-sm-6">
            <div class="assign-modal-content">

              <!-- Modal Header -->
              <div class="modal-header">
                <button class="btn btn-primary" type="submit">Add</button>
                <button class="btn btn-primary" type="button" onclick="document.getElementById('assignModal').style.display='none'">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="assign-modal-body" style="height:400px;">
                <div class="row" style="height:100%;">
                  <!-- Leftdiv card -->
                  <div class="card leftdiv col-sm-5">
                     <div class="" style="background: #88888829;height:15%;position:static;width:100%;margin-left:0px;">
                        <form class="form-inline my-2 my-lg-0" style="padding-top:1%;width:100%;" >
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                          </form>
                     </div>
                     <hr />
                     <div class="card-body">

                     </div>
                  </div>

                  <!-- Rightdiv card-->
                  <div class="card rightdiv col-sm-5">
                    <label>Select a file to upload...</label>
                    <input type="file" name="fileUpload" onchange="setFileName(event.target.files[0].name)" />
                  </div>
                </div>
              </div>


              <!-- Modal footer -->
              <div class="modal-footer">
              </div>

            </div>
          </div>
        </div>

      </div>

tempapp/templates/create_folder.html
<!-- Create folder Modal -->
<div class="modal fade" id="folderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" >
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Enter the name of the folder</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="POST">
        {% csrf_token %}
          <div class="">
<!--            {{ site_folder_form.folder_name }}-->
            {{ folder_form.folder_name }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Create folder</button>
          </div>
      </form>
    </div>
  </div>
</div>

tempapp/templates/navbar.html
{% url 'siteapp:index' as index %}
{% url 'siteapp:task' as task %}
{% url 'sites' as sites %}
{% url 'siteapp:repository' as repository %}
{% url 'siteapp:taskpage' as taskpage %}
<style> .active {background-color:white;} </style>
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <h5><span class="navbar-toggler-icon" style="height:30px;"><h5 style="margin-left: 50px;">Menu</h5></span></h5>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item {% if request.path == index %} active {% endif %}">
              <a class="nav-link text-primary" href="{% url 'siteapp:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-primary" href="" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Sites
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item fa fa-globe" href="" data-toggle="modal" data-target="#sitemodal"><r>Create site</r></a>
                  <a class="dropdown-item fa fa-folder" href="{% url 'siteapp:repository' %}"><r>Repository</r></a>
                  <a class="dropdown-item" href="{% url 'siteapp:sites' %}">My Site</a>
                  <div class="dropdown-divider"></div>
                    <a class="dropdown-item fa fa-tasks" href="{% url 'siteapp:task' %}"><r>My Task</r></a>
                </div>
            </li>
            <li class="nav-item {% if request.path == task %} active {% endif %}">
              <a class="nav-link text-primary" href="{% url 'siteapp:task' %}">Tasks</a>
            </li>
            <li class="nav-item {% if request.path == repository %} active {% endif %}">
              <a class="nav-link text-primary" href="{% url 'siteapp:repository' %}">Repository</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-primary" href="{% url 'password_change' %}">Change Password</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle fa fa-user text-primary" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item fa fa-globe" href="{% url 'password_change' %}"><r>Change Password</r></a>
                <a class="dropdown-item fa fa-user" href="#"><r>Profile</r></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item fa fa-sign-out" href="{% url 'logout' %}"><r>Logout</r></a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

tempapp/templates/sitemodal.html
  <!-- Modal -->
  {% block style %}
  <style>
  .sidenav{z-index:-1;}
      .modal{
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        padding-top: 60px;
      }

      .sitemodal {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
      }

      .sitemodal .modal-content {
        margin: auto auto 5% auto; /* 5% from the top, 5% from the bottom and centered */
        border: 1px solid #888;
        width: 350px; /* Could be more or less, depending on screen size */
      }

    /* Add Zoom Animation */
      .animate {
        -webkit-animation: animatezoom 0.6s;
        animation: animatezoom 0.6s
      }

      @-webkit-keyframes animatezoom {
        from {-webkit-transform: scale(0)}
        to {-webkit-transform: scale(1)}
      }

      @keyframes animatezoom {
        from {transform: scale(0)}
        to {transform: scale(1)}
      }
      #id_site_visibility {
        list-style-type:none;
      }
  </style>
  {% endblock %}
  <div class="modal sitemodal" id="sitemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true" style="width:100%;">
    <div class="modal-dialog" role="document" style="width:100%;">
        <form class="modal-content animate" action="" method="post">
            {% csrf_token %}
          <div class="container" style="padding-top: 5%; padding-left:10%; padding-right: 8%; background-color:white;">
<!--                {{ siteform.as_p }}-->
              <label for="id_site_name"><b>Site Name/Title</b></label>
                {{ siteform.site_name }}
              <label for="id_site_id"><b>Site_id</b></label>
                {{ siteform.site_id }}
              <label for="id_description"><b>Description</b></label>
                {{ siteform.description }}
              <label for="id_site_visibility"><b>Visibility</b></label>
                {{ siteform.site_visibility }}

              <script type="text/javascript">
<!--                  var el = document.getElementsByTagName ('label');-->
<!--                for(var x=0; x<el.length; x++)-->
<!--                {-->
<!--                    if (el[x].innerHTML == "Site name:")-->
<!--                        el[x].innerHTML = "<b>Site Name/Title</b>"-->
<!--                    if (el[x].innerHTML == "Site id:")-->
<!--                        el[x].innerHTML = "<b>Site_id</b>"-->
<!--                    if (el[x].innerHTML == "Description:")-->
<!--                        el[x].innerHTML = "<b>Description</b>"-->
<!--                    if (el[x].innerHTML == "Site visibility:")-->
<!--                        el[x].innerHTML = "<b>Visibility</b>"-->
<!--    -->
<!--                }-->
                //Query all input fields
<!--                var form_fields = document.getElementsByTagName('input')-->
<!--                form_fields[1].placeholder="name of site...";-->
<!--                form_fields[2].placeholder="site_id...";-->
<!--                form_fields[3].placeholder="description...";-->
              </script>
            <br />
            <button type="submit">Create site</button>
            <button type="button" class="cancelbtn" onclick="document.getElementById('sitemodal').style.display='none'" data-dismiss="modal">Cancel</button>
      </div>
      </form>
    </div>
  </div>

tempapp/templates/uploadmodal.html
{% load static %}
<!--File upload modal-->
<div class="container">
  <!-- The Modal -->
  <div class="modal" id="myModal">
    <div class="modal-dialog">

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">File upload</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <div class="row">
            <div class="col-1">
                <img id="aud" src="{% static 'images/fileicons/audioicon.jpeg' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="def" src="{% static 'images/fileicons/deficon.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="docs" src="{% static 'images/fileicons/docs.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="html" src="{% static 'images/fileicons/htmlicon.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="img" src="{% static 'images/fileicons/imageicon.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="pdf" src="{% static 'images/fileicons/pdficon.png' %}" height="50" width="50" alt="icon" style="display:none;">
                <img id="pow" src="{% static 'images/fileicons/powicon.png' %}" height="50" width="50" alt="icon" style="display:none;">
            </div>
            <div class="col" style="padding-top: 13px;">
                <h6 id="file" name="file"></h6>
            </div>
          </div>
          <div style="text-align: center; border: 1px dashed rgb(9, 216, 147);">
            <label for="id_filepath">Select a file to upload...</label>
              Select
<!--            <input type="file" name="fileUpload" onchange="setFileName(event.target.files[0].name)" id="upload" />-->
              {{ form.filepath }}

              <script type="text/javascript">
                document.getElementById('id_filepath').style.display = "none";
                document.getElementById('id_filepath').addEventListener("change", function(){setFileName(event.target.files[0].name)});
              </script>
          </div>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary" style="width:100%;color:white;">
            <i class="fas fa-upload" style="color: white;"></i>Upload</button>
        </div>

      </div>
        </form>
    </div>
  </div>

</div>